name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
      - name: Set executable permissions to fix errors
        run: |
          # Remove executable permissions from non-executable files
          run: chmod +x .git/hooks/*
