name: Pre-commit Hook

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger this on
  pull_request:
    branches:
      - main  # or whichever branch you want to trigger this on

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Use the required Python version

      # Step 3: Install required Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Step 4: Install the pre-commit hooks
      - name: Install pre-commit hooks
        run: pre-commit install

      # Step 5: Run pre-commit hooks on all files
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files || true  # This ensures it won't fail the workflow

      # Step 6: Collect and report any pre-commit errors
      - name: Report pre-commit errors (if any)
        run: |
          if [[ $(pre-commit run --all-files --verbose | grep -i 'failed') ]]; then
            echo "Pre-commit hooks failed. Please fix the issues."
          else
            echo "All pre-commit hooks passed!"
          fi

      # Optional Step 7: Always complete the job (even if pre-commit fails)
      - name: Always complete job
        run: echo "Job completed. Pre-commit ran successfully, or there were failures that didn't stop the workflow."
