name: tfsec
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Run tfsec scan and generate SARIF report
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif
          full_repo_scan: true

      - name: tfsec commenter for PR
        if: github.event_name == 'pull_request'
        uses: tfsec/tfsec-pr-commenter-action@v1.3.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform security scan Advanced
        uses: triat/terraform-security-scan@v3.1.0
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tfsec_actions_comment: true
          tfsec_output_format: sarif
        continue-on-error: true